"""
Pydantic models for task state management, reports, and citations.
"""
from typing import List, Dict, Optional, Literal
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


class TaskStatus(str, Enum):
    """Task execution status"""
    PLANNING = "planning"
    EXECUTING = "executing"
    PUBLISHING = "publishing"
    DONE = "done"
    FAILED = "failed"


class Citation(BaseModel):
    """Source citation with metadata"""
    id: str  # e.g., "S1", "S2"
    title: str
    url: str
    authors: Optional[str] = None
    date: Optional[str] = None
    snippet: str  # Brief excerpt or quote
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "S1",
                "title": "GPT-4 Technical Report",
                "url": "https://arxiv.org/abs/2303.08774",
                "authors": "OpenAI",
                "date": "2023-03-15",
                "snippet": "GPT-4 is a large-scale, multimodal model..."
            }
        }


class SubQuestion(BaseModel):
    """Sub-question generated by planner"""
    question: str
    status: Literal["pending", "processing", "completed", "failed"] = "pending"
    summary: Optional[str] = None
    sources: List[Citation] = Field(default_factory=list)


class Report(BaseModel):
    """Final research report with citations"""
    title: str
    content: str  # Markdown formatted report with inline citations [S1], [S2]
    word_count: int
    citations: List[Citation] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "title": "Deep Learning in Healthcare: A Comprehensive Review",
                "content": "# Introduction\n\nDeep learning has revolutionized healthcare [S1]...",
                "word_count": 2543,
                "citations": [],
                "generated_at": "2025-11-09T10:30:00Z"
            }
        }


class TaskState(BaseModel):
    """Complete state for a research task"""
    task_id: str
    query: str
    status: TaskStatus = TaskStatus.PLANNING
    sub_questions: List[SubQuestion] = Field(default_factory=list)
    report: Optional[Report] = None
    error: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Progress tracking
    current_step: str = "Initializing..."
    progress_percentage: int = 0
    
    def update_progress(self, step: str, percentage: int):
        """Update progress tracking"""
        self.current_step = step
        self.progress_percentage = percentage
        self.updated_at = datetime.utcnow()


class CreateReportRequest(BaseModel):
    """Request model for creating a new report"""
    query: str = Field(..., min_length=10, max_length=500)
    
    class Config:
        json_schema_extra = {
            "example": {
                "query": "What are the latest advances in quantum computing and their implications for cryptography?"
            }
        }


class StatusResponse(BaseModel):
    """Response for status endpoint"""
    task_id: str
    status: TaskStatus
    current_step: str
    progress_percentage: int
    sub_questions_count: int = 0
    completed_questions: int = 0
